version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmqCompose"
    image: rabbitmq:4.0-rc-management
    ports:
        #RabbitMQ instance
      - "5672:5672"
        #Web interface
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    # volumes:
    #   - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
    #   - ./rabbitmq/logs:/var/log/rabbitmq
    #   - ./rabbitmq/config:/etc/rabbitmq